package com.example.mapper;

import com.example.domain.Sample;
import com.example.domain.SampleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SampleMapper {
	
	List<Sample> findAll();
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon May 11 15:39:21 JST 2020
     */
    int countByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon May 11 15:39:21 JST 2020
     */
    int deleteByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon May 11 15:39:21 JST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon May 11 15:39:21 JST 2020
     */
    int insert(Sample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon May 11 15:39:21 JST 2020
     */
    int insertSelective(Sample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon May 11 15:39:21 JST 2020
     */
    List<Sample> selectByExample(SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon May 11 15:39:21 JST 2020
     */
    Sample selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon May 11 15:39:21 JST 2020
     */
    int updateByExampleSelective(@Param("record") Sample record, @Param("example") SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon May 11 15:39:21 JST 2020
     */
    int updateByExample(@Param("record") Sample record, @Param("example") SampleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon May 11 15:39:21 JST 2020
     */
    int updateByPrimaryKeySelective(Sample record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sample
     *
     * @mbggenerated Mon May 11 15:39:21 JST 2020
     */
    int updateByPrimaryKey(Sample record);
}